title: Site

columns:
  main:
    width: 2/3
    sections:
      collections:
        type: pages
        label: Collections
        sortBy: title asc
        query: site.children.listed

  sidebar:
    width: 1/3
    sections:
      system:
        type: pages
        label: System Pages
        sortBy: title asc
        query: site.children.unlisted
